-- MySQL Script generated by MySQL Workbench
-- Mon 21 May 2018 02:44:35 PM CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema dz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dz` DEFAULT CHARACTER SET utf8 ;
USE `dz` ;

-- -----------------------------------------------------
-- Table `dz`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`forum` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL COMMENT '名称',
  `post_count` INT NOT NULL DEFAULT 0 COMMENT '帖子数',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `auth_key` VARCHAR(45) NULL,
  `password_hash` VARCHAR(60) NULL,
  `password_reset_token` VARCHAR(255) NULL,
  `email` VARCHAR(45) NOT NULL,
  `credit` INT NOT NULL,
  `status` TINYINT(1) NOT NULL DEFAULT 1,
  `group` SMALLINT(3) NOT NULL DEFAULT 1,
  `created_at` INT NULL,
  `updated_at` INT NULL,
  `last_logined_at` INT NULL,
  PRIMARY KEY (`id`, `status`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz`.`post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `forum_id` INT NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `content` TEXT NOT NULL,
  `view_count` INT NOT NULL DEFAULT 0,
  `comment_count` INT NOT NULL DEFAULT 0,
  `created_at` INT NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_forum_idx` (`forum_id` ASC),
  INDEX `fk_post_user1_idx` (`created_by` ASC),
  CONSTRAINT `fk_post_forum`
    FOREIGN KEY (`forum_id`)
    REFERENCES `dz`.`forum` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_user1`
    FOREIGN KEY (`created_by`)
    REFERENCES `dz`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz`.`post_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`post_favorite` (
  `post_id` INT NOT NULL,
  `created_at` INT NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`post_id`),
  CONSTRAINT `fk_post_favorite_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dz`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz`.`comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz`.`post_comment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`post_comment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `post_id` INT NOT NULL,
  `comment_id` INT NOT NULL,
  `created_at` INT NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_post_comment_comment1_idx` (`comment_id` ASC),
  CONSTRAINT `fk_post_comment_post1`
    FOREIGN KEY (`post_id`)
    REFERENCES `dz`.`post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_post_comment_comment1`
    FOREIGN KEY (`comment_id`)
    REFERENCES `dz`.`comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dz`.`post_comment_favorite`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dz`.`post_comment_favorite` (
  `post_comment_id` INT NOT NULL,
  `created_at` INT NULL,
  `created_by` INT NULL,
  PRIMARY KEY (`post_comment_id`),
  CONSTRAINT `fk_post_comment_favorite_post_comment1`
    FOREIGN KEY (`post_comment_id`)
    REFERENCES `dz`.`post_comment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
